name: 🐛 Bug Report
description: Create a report to help us improve
title: '[BUG] '
labels: ['bug', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Set configuration '...'
        3. Observe error '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: e.g., Ubuntu 22.04, macOS 13.0, Windows 11
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: DeviceSimulator Version
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      placeholder: e.g., 1.24.5
    validations:
      required: false

  - type: dropdown
    id: installation-method
    attributes:
      label: Installation Method
      options:
        - Debian package
        - Docker
        - Source build
        - Binary download
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: 📄 Configuration
      description: Please provide your configuration file content (remove sensitive data)
      placeholder: |
        [general]
        interface=eth0
        clientmac=...
      render: ini
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: 📝 Logs
      description: Please provide relevant log output
      placeholder: Paste logs here...
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 🔍 Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have provided all requested information
          required: true
        - label: I have tested with the latest version
          required: false
        - label: I have removed sensitive information from logs/config
          required: true